### ISSUE TITLE
[Question] - Does It could connect to another smart scales?

### ISSUE THREAD

**Issue by CyRamos** [zibous/ha-miscale2#2]
Hey
I have Renpho Smart Scale & Rasberry pi 4.
https://www.amazon.com/RENPHO-Bluetooth-Bathroom-Composition-Smartphone/dp/B01N1UX8RW

I'd like to know if this code could integrate into my scale because both of them work on Bluetooth signals. 
My goal is to be able eventually to see the scale data in my Obsidian Vault. 
Thanks.

**Comment by zibous** [comment]
> I'd like to know if this code could integrate into my scale because both of them work on Bluetooth signals.

Negativ, do not work because the BLE Protocoll is not the same as the miscale`s

You can try the app `openScale`.
see: 

https://github.com/oliexdev/openScale
https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale
https://medevel.com/openscale/
